### PR TITLE
Remove search bar from bottom/and add search bar to login mode

### PR DESCRIPTION
**Pull request by sahdasamier**

### CODE REVIEW

**Review by gvelez17 — APPROVED** [review]

**Review by ArnobChowdhury — CHANGES_REQUESTED** [review]
If we are gonna have the search bar regardless of the auth status, then it should not be inside the logic of `{isAuth && ...}`. Plz check [https://github.com/Whats-Cookin/trust_claim/pull/138](url)

**Review by ArnobChowdhury — CHANGES_REQUESTED** [review]
If we are gonna have the search bar regardless of the auth status, then it should not be inside the logic of `{isAuth && ...}`. Plz check [https://github.com/Whats-Cookin/trust_claim/pull/138](url)

**Review by ArnobChowdhury — CHANGES_REQUESTED** [review]
If we are gonna render the search bar regardless of auth status, then we should not put Search bar inside `{ isAuth && ...}` logic. Please check my pr https://github.com/Whats-Cookin/trust_claim/pull/138

**Review by ArnobChowdhury — APPROVED** [review]
LGTM.

**Pull request merged**
