### PR TITLE
feat(front): Update report UI

### PR DESCRIPTION
**Pull request by husamahmud**
Screenshot 2024-06-02 at 3 03 38 AM
Screenshot 2024-06-02 at 3 03 47 AM

### CODE REVIEW

**Comment by AhmedAbdelmenam** [comment]
please solve the Conflict

**Comment by husamahmud** [comment]
> please solve the Conflict

ON IT.

**Comment by husamahmud** [comment]
> please solve the Conflict

Done.

**Comment by AhmedAbdelmenam** [comment]
can you make a pr direct to this repo ??

**Comment by husamahmud** [comment]
> can you make a pr direct to this repo ??

They are the same, is there a problem with you?

**Comment by dev-mhany** [comment]
@AhmedAbdelmenam 
LGTM please review and merge
Screenshot 2024-06-08 011514
Screenshot 2024-06-08 011454

**Pull request closed without merging**
