### PR TITLE
Comment

### PR DESCRIPTION
**Pull request by romeoscript**

### CODE REVIEW

**Review by dev-ahmedhany — CHANGES_REQUESTED** [review]
DO NOT UPLOAD package-lock changes if you havn't added any new packages
also
remove tailwind classes; we will remove this package, we are useing material-ui

**Comment by romeoscript** [comment]
The packages have been there on the initial upload not this particular pr, and for the tailwind, would remove the classes but not now ,have been used in other components other than this prolly after the demo

**Comment by dev-ahmedhany** [comment]
the package-lock edited here https://github.com/Whats-Cookin/trust_claim/pull/68/commits/784fac3cdbc58210d9a320f87232636c90b20395 ... have a look
and for tailwind ... OK I can wait until we remove it from everywhere but we can't accept new code using it, it will make our job harder in the future.

**Comment by dev-ahmedhany** [comment]
If i accepted package-lock changes it wil make conflict with every other package update PRs ,  and github can't resolve this confilct automatically

**Comment by romeoscript** [comment]
Ok I would migrate the change to another branch without package-lock

**Comment by dev-ahmedhany** [comment]
and tailwind
Thank you

**Comment by romeoscript** [comment]
For now let tailwind be there cos of time , I would do the change for tailwind later , cos there are other pressing stuffs  and it's not only on that component

**Pull request closed without merging**
