### PR TITLE
Updated Navbar

### PR DESCRIPTION
**Pull request by AmrNabel**

### CODE REVIEW

**Review by sahdasamier — CHANGES_REQUESTED** [review]
there is a significant top margin in the Ipad mode and other devices bigger than 540, so part of the graph is hidden behind it,  and it is not central at all devices "
so please try to solve it

**Review by sahdasamier — CHANGES_REQUESTED** [review]
you made an issue with login and creating claim pages, the navbar take part of the form till the title all hidden behind it, and the login form is in the navbar, and part of it is hidden too 
please find out the problem and solve it

**Comment by AmrNabel** [comment]
ok no problem, I fixed it

**Review by sahdasamier — CHANGES_REQUESTED** [review]
you made a graph so small

**Review by sahdasamier — APPROVED** [review]

**Pull request merged**
