### PR TITLE
claimnode

### PR DESCRIPTION
**Pull request by sahdasamier**

### CODE REVIEW

**Review by dev-ahmedhany — CHANGES_REQUESTED** [review]
just remove package-lock.json changes

**Comment by romeoscript** [comment]
@dev-ahmedhany i don't think package -lock is an issue

**Comment by sahdasamier** [comment]
I realized that I deleted all file from git not changes only so I add that by merging master with , you can see that in update 2

**Review by dev-ahmedhany — CHANGES_REQUESTED** [review]
why this branch contains "comment" feature changes?
please each branch should have only one thing, unless they are related

**Comment by dev-ahmedhany** [comment]
@romeoscript package-lock can be changed by  alot of things, like yarn npm pnpm ..etc , if every person uploads it's version that will be a miss
and how any why you code is here?

**Comment by sahdasamier** [comment]
No, this branch doesn't have "comment" feature changes, I removed all comment like you said , me , actually I can't get where is the problem

**Comment by sahdasamier** [comment]
I made merge master to my branch ,then Rome's code it is appearing, and I don't know how is that happening, but I think it is the last updates of master, I didn't pull before , so it is appearing now , I am not sure

**Pull request closed without merging**
