### PR TITLE
Implement google auth

### PR DESCRIPTION
**Pull request by TutTrue**
## Description

Please provide a brief summary of the changes in this PR.

## Type of Change

- [ ] Bug fix
- [X] New feature
- [ ] Test case
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [ ] I have added necessary documentation (if applicable)

## 4- steps to test ?

login with google in both fullscreen and mobile view

Please provide a brief summary of the steps required to test the changes in this PR.

I have added login with google instead of github

## 5- results ?

Please provide a brief summary of the results after testing the changes in this PR.

## 7- screenshots ?
image
image

Please provide screenshots of the results after testing the changes in this PR.

### CODE REVIEW

**Review by Kholoudxs55kh — APPROVED** [review]

**Comment by AhmedAbdelmenam** [comment]
please when you need to install any package install it in a single pr and I will merge it immediately

**Comment by AhmedAbdelmenam** [comment]
now we use just yarn we didn't use npm

**Comment by AhmedAbdelmenam** [comment]
Screenshot 2024-08-23 at 8 54 31 PM
Screenshot 2024-08-23 at 8 54 43 PM

please the icon i can show it like this I tested it with Google Chrome and Safari the same white icon

**Comment by TutTrue** [comment]
Icon is working don't forget to npm I or install the dep with yarn

**Comment by AhmedAbdelmenam** [comment]
i didn't forget that and it's not working with Mohamed also

**Pull request merged**
