### PR TITLE
[FEATURE]: Implement SignInAlert

### PR DESCRIPTION
**Pull request by husamahmud**
## Description
Show a popup when the user wants to create a claim and is not authenticated.

## Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Test case
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [x] I have added necessary documentation (if applicable)

## 4- steps to test ?

Please provide a brief summary of the steps required to test the changes in this PR.

## 5- results ?

Please provide a brief summary of the results after testing the changes in this PR.

## 7- screenshots ?
image
image
image

### CODE REVIEW

**Comment by AhmedAbdelmenam** [comment]
Great work Hossam, but we want this popup to appear when we click on create claim.
and let create claim be always visible.
Screenshot (39)

**Comment by husamahmud** [comment]
Oh, i forget to remove it after testing, check it now :)

**Comment by AhmedAbdelmenam** [comment]
we need the two icons to create a claim to always be visible
Screenshot 2024-08-27 at 2 37 45 PM
and when we click on it i can show the popup

**Review by AhmedAbdelmenam — APPROVED** [review]
great

**Pull request merged**
